{{- $user := .Values.postgresql.auth.applicationUser -}}
{{- $password := .Values.postgresql.auth.applicationPassword -}}
{{- $host := .Values.postgresql.name -}}
{{- $port := .Values.postgresql.port -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.databaseConnections.secretName }}
type: Opaque
stringData:
  CATALOG_DB_DSN: {{ printf "postgres://%s:%s@%s:%v/catalog_db?sslmode=disable" $user $password $host $port | quote }}
  INVENTORY_DB_URL: {{ printf "postgres://%s:%s@%s:%v/inventory_db" $user $password $host $port | quote }}
  ORDER_DB_DSN: {{ printf "dbname=order_db user=%s password=%s host=%s port=%v" $user $password $host $port | quote }}
  PAYMENT_DB_URL: {{ printf "Host=%s;Port=%v;Database=payment_db;Username=%s;Password=%s" $host $port $user $password | quote }}
  NOTIFICATION_DB_URL: {{ printf "postgres://%s:%s@%s:%v/notification_db" $user $password $host $port | quote }}
