apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgresql.auth.secretName }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.postgresql.auth.postgresUser | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.auth.postgresPassword | quote }}
  MICROAPP_USER: {{ .Values.postgresql.auth.applicationUser | quote }}
  MICROAPP_PASSWORD: {{ .Values.postgresql.auth.applicationPassword | quote }}
