apiVersion: v1
kind: ConfigMap
metadata:
  name: analytics-service-config
data:
  CATALOG_URL: "http://catalog-service:8082"
  INVENTORY_URL: "http://inventory-service:8083"
  ORDER_URL: "http://order-service:8084"
  PAYMENT_URL: "http://payment-service:8085"