apiVersion: v1
kind: ServiceAccount
metadata:
  name: catalog-service

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: catalog-reader
rules:
  - apiGroups: [""]
    resources:
      - pods
    verbs:
      - get
      - list
      - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: catalog-reader-binding

subjects:
  - kind: ServiceAccount
    name: catalog-service

roleRef:
  kind: Role
  name: catalog-reader
  apiGroup: rbac.authorization.k8s.io